// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpmgppwxzuaudonhwjeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwbWdwcHd4enVhdWRvbmh3amVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNTc5NzUsImV4cCI6MjA2MTgzMzk3NX0.dgiYmC42RQK93Ho-Stgb_OoVbGky_ghY-oabDvXYW24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);